export const employees = [
    {
        id: '1',
        name: 'Carlos Silva',
        role: 'Gerente',
        department: 'Administrativo',
        status: 'ATIVO',
        vacationBalance: 23,
        acquisitionPeriodStart: '2025-08-12',
        acquisitionPeriodEnd: '2026-07-12',
        grantPeriodStart: '2026-08-12',
        grantPeriodEnd: '2027-08-12',
    },
    {
        id: '2',
        name: 'Ana Paula Costa',
        role: 'Assessor',
        department: 'RH',
        status: 'ATIVO',
        vacationBalance: 30,
        acquisitionPeriodStart: '2025-12-15',
        acquisitionPeriodEnd: '2026-12-14',
        grantPeriodStart: '2026-12-15',
        grantPeriodEnd: '2027-12-15',
    },
    {
        id: '3',
        name: 'Fernanda Oliveira',
        role: 'Analista',
        department: 'Financeiro',
        status: 'ATIVO',
        vacationBalance: 0,
        acquisitionPeriodStart: '2025-12-22',
        acquisitionPeriodEnd: '2026-12-21',
        grantPeriodStart: '2026-12-22',
        grantPeriodEnd: '2027-12-22',
    },
    {
        id: '4',
        name: 'Roberto Santos',
        role: 'Técnico',
        department: 'TI',
        status: 'ATIVO',
        vacationBalance: 30,
        acquisitionPeriodStart: '2025-12-29',
        acquisitionPeriodEnd: '2026-12-28',
        grantPeriodStart: '2026-12-29',
        grantPeriodEnd: '2027-12-29',
    },
    {
        id: '5',
        name: 'Mariana Souza',
        role: 'Analista',
        department: 'Jurídico',
        status: 'ATIVO',
        vacationBalance: 30,
        acquisitionPeriodStart: '2025-12-01',
        acquisitionPeriodEnd: '2026-11-30',
        grantPeriodStart: '2026-12-01',
        grantPeriodEnd: '2027-12-01',
    },
    {
        id: '6',
        name: 'Plínio Ferreira',
        role: 'Gerente',
        department: 'Operações',
        status: 'ATIVO',
        vacationBalance: 30,
        acquisitionPeriodStart: '2025-12-29',
        acquisitionPeriodEnd: '2026-12-28',
        grantPeriodStart: '2026-12-29',
        grantPeriodEnd: '2027-12-29',
    },
];

export const leaves = [
    {
        id: '1',
        employeeId: '1',
        employeeName: 'Carlos Silva',
        employeeRole: 'Gerente',
        type: 'FERIAS',
        startDate: '2025-12-31',
        endDate: '2026-01-06',
        daysOff: 7,
        workDaysOff: 4,
        efficiency: 57,
        status: 'PLANEJADO',
    },
    {
        id: '2',
        employeeId: '2',
        employeeName: 'Ana Paula Costa',
        employeeRole: 'Assessor',
        type: 'ALISTAMENTO_ELEITORAL',
        startDate: '2025-12-31',
        endDate: '2026-01-13',
        daysOff: 14,
        workDaysOff: 9,
        efficiency: 64,
        status: 'PLANEJADO',
    },
    {
        id: '3',
        employeeId: '3',
        employeeName: 'Fernanda Oliveira',
        employeeRole: 'Analista',
        type: 'FERIAS',
        startDate: '2026-01-13',
        endDate: '2026-02-11',
        daysOff: 30,
        workDaysOff: 22,
        efficiency: 73,
        status: 'PLANEJADO',
    },
    {
        id: '4',
        employeeId: '4',
        employeeName: 'Roberto Santos',
        employeeRole: 'Técnico',
        type: 'FALECIMENTO',
        startDate: '2025-12-09',
        endDate: '2025-12-17',
        daysOff: 9,
        workDaysOff: 7,
        efficiency: 78,
        status: 'ATIVO',
        notes: 'Falecimento de familiar',
    },
];

export const holidays = [
    { id: '1', date: '2026-01-01', name: 'Ano Novo', type: 'NACIONAL' },
    { id: '2', date: '2026-02-16', name: 'Carnaval', type: 'NACIONAL' },
    { id: '3', date: '2026-02-17', name: 'Carnaval', type: 'NACIONAL' },
    { id: '4', date: '2026-02-18', name: 'Quarta-feira de Cinzas', type: 'PONTO_FACULTATIVO' },
    { id: '5', date: '2026-04-03', name: 'Sexta-feira Santa', type: 'NACIONAL' },
    { id: '6', date: '2026-04-21', name: 'Tiradentes', type: 'NACIONAL' },
    { id: '7', date: '2026-05-01', name: 'Dia do Trabalho', type: 'NACIONAL' },
    { id: '8', date: '2026-06-04', name: 'Corpus Christi', type: 'NACIONAL' },
    { id: '9', date: '2026-09-07', name: 'Independência do Brasil', type: 'NACIONAL' },
    { id: '10', date: '2026-10-12', name: 'Nossa Senhora Aparecida', type: 'NACIONAL' },
    { id: '11', date: '2026-11-02', name: 'Finados', type: 'NACIONAL' },
    { id: '12', date: '2026-11-15', name: 'Proclamação da República', type: 'NACIONAL' },
    { id: '13', date: '2026-11-20', name: 'Consciência Negra', type: 'NACIONAL' },
    { id: '14', date: '2026-12-25', name: 'Natal', type: 'NACIONAL' },
];

export const companyEvents = [
    { id: '1', date: '2026-01-15', name: 'Reunião de Planejamento Anual', type: 'REUNIAO' },
    { id: '2', date: '2026-02-10', name: 'Treinamento de Segurança', type: 'TREINAMENTO' },
    { id: '3', date: '2026-03-20', name: 'Confraternização de Aniversário', type: 'EVENTO' },
];

export const departments = [
    'Administrativo',
    'RH',
    'Financeiro',
    'TI',
    'Jurídico',
    'Operações',
    'Comercial',
    'Marketing',
];

export const roles = [
    'Gerente',
    'Assessor',
    'Analista',
    'Técnico',
];

export const leaveTypes = [
    'FERIAS',
    'LICENCA_MEDICA',
    'LICENCA_MATERNIDADE',
    'LICENCA_PATERNIDADE',
    'CASAMENTO',
    'FALECIMENTO',
    'ESTUDO',
    'DOACAO_SANGUE',
    'COMPARECIMENTO_JUIZO',
    'ALISTAMENTO_ELEITORAL',
    'ABONO',
    'ACIDENTE_TRABALHO',
    'DISPENSA',
    'FOLGA',
    'OUTRO',
];
